name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the artifacts with the docker image
      run: docker-compose up
    - name: Package built file
      run: |
        mkdir -p build
        cp draft-ietf-gnap-core-protocol.html build/index.html
    - name: Deploy draft to Netlify
      uses: South-Paw/action-netlify-deploy@v1.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_ID }}
        build-dir: './build'
        draft: true
        comment-on-commit: true
        comment-on-pull-request: true
